# 22/04/2026
# Changing the file with 1 sample -> 1 contig(or read) -> x ARGs
# into a file with  1 sample -> 1 contig(or read) -> 1 ARG
# Input : 'samples_taxo_coloc.csv'
# It is the file 'all_samples_merged.csv' generated by Telcomb/blast but 
# rearranged to get only the colomn sample,read,ARG,MGE(s),blast_species. 
# It is possible to add a filter to get only the ARG with the WHO
# classification 'Authorized only for Humans'. 
# Out : 'all_samples_one_ARG_per_line.csv'

# Part 1: Importing the necessary packages and data -----------------------

library(dplyr)
library(tidyr)
library(readr)
library(stringr)

df <- read_csv(
  "samples_taxo_coloc.csv",
  col_types = cols(.default = "c")
)

# Part 2: Data cleaning and formatting ------------------------------------

df_long <- df %>%
  mutate(
    ARG = str_replace_all(ARG, "\r|\n", ""),   # enlève retours ligne
    ARG = str_replace_all(ARG, "\\\\", "")     # enlève les backslashes
  ) %>%
  separate_rows(ARG, sep = ";") %>%            # 1 ligne = 1 ARG
  mutate(ARG = str_trim(ARG)) %>%               # nettoyage espaces
  filter(ARG != "", !is.na(ARG))                # sécurité

# Filtering colomns and renaming 
final_df <- df_long %>%
  transmute(
    sample = sample,
    contig = read,
    arg = ARG,
    `mge(s)` = `MGE(s)`,
    species = blast_species,
    other_info = blast_infos_subs_strain
  )

# Part 3: Saving output------------ ------------------------------------
write_csv(final_df, "all_samples_one_ARG_per_line.csv")
