# 17/05/2026
# Barplot of the number of contigs by samples generated by TELCoMB

# Part 1: Importing the necessary packages and data -----------------------
library(readr)
library(tidyr)
library(ggplot2)
library(ggforce)
library(tibble)

contigs <- read.csv("contigs.csv",dec = ".", sep = ",", header = FALSE)
contigs=contigs[,-3]

# Part 2: rearranging data ------------------------------------------------

mean(contigs$V2)
sum(contigs$V2)
summary(contigs)

contigs.env <- read.csv("sample_collection.csv",dec = ",", sep = ";", header = TRUE)
contigs$bioproject <- contigs$V2
contigs$bioproject <- contigs.env$bioproject[match(contigs$V1,contigs.env$sample)]
contigs[contigs$V1=="SRR13801805", "bioproject"] <- "PRJNA704713"

# Part 3:  coloring by Bioproject ------------------------------------------

color_map <- c(
  "PRJEB65292" = "red",
  "PRJEB77409" = "steelblue",
  "PRJNA388572" = "green",
  "PRJNA704713" = "purple"
)

bar_colors <- color_map[contigs$bioproject]
n = as.character(nrow(contigs))

# Part 4:  Plotting --------------------------------------------------------

barplot(
  contigs$V2,
  names.arg = contigs$V1,
  col = bar_colors,
  las = 3, # labels verticaux
  main = paste("Number of contigs generated by metaSPADes using TELCoMB protocol,\n",n,"samples"),
  sub = "Metagenome samples from kefir products",
  ylab = "Number of contigs",
  cex.names = 0.5
)

legend(
  "topleft",
  legend = names(color_map),
  fill = color_map,
  title = "Bioproject",
  cex = 0.5
)
dev.off()

# Save
pdf("barplot_contigs.pdf", width = 12, height = 4)
layout(matrix(c(1,2), ncol = 1), heights = c(3,1.5))
